### ISSUE TITLE
tmux 2.2 includes this change

### ISSUE THREAD

**Issue by Kriechi** [NHDaly/tmux-scroll-copy-mode#18] opened 2016-05-30 19:53 UTC
I think tmux 2.2 reverted / replaced the behaviour and this plugin is not needed anymore on tmux 2.2.
Can you verify and confirm this, and maybe add a notice to the readme or some conditional check to the code?

Thanks.

**Comment by NHDaly** [comment] 2016-06-03 03:47
Hmm, it doesn't look like it based on the change log?:
https://raw.githubusercontent.com/tmux/tmux/master/CHANGES

**Comment by NHDaly** [comment] 2016-06-03 03:47
What makes you say so?

**Comment by Kriechi** [comment] 2016-06-03 07:33
This commit: https://github.com/tmux/tmux/commit/ddbc4a0f6ca0c6486a038ce91971212785d44744

**Comment by khashayar** [comment] 2016-06-07 12:52
I installed the latest version and I can confirm that scrolling is fixed without using this plugin!

**Comment by NHDaly** [comment] 2016-09-15 03:57
Thanks everyone for catching this, you're right -- `2.2` mostly restores the `2.0` mouse behavior.

In aa6b4ed46b53e12 I've changed the name of the repo from `tmux-scroll-copy-mode` to `tmux-better-mouse-mode`, because I think the value of this plugin isn't just restoring old behavior anymore, but it's now the cool options to configure mouse behavior that it provides.

In e07eca0 I've added a note to the README that `tmux` 2.2 mostly restores the `2.0` mouse behavior. :)

In #16 we were thinking that maybe I should enable some of the better mouse behavior options by default, which I'm still considering doing. What do you all think?

**Closed as completed** 2016-09-15 03:58 UTC

**Comment by zeorin** [comment] 2016-09-16 05:27
I think yes: enable those options by default. Renaming the repo is quite indicative of big changes.
